### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by JChrist** [jeroentrappers/dart_dgc_validate#6]
Hi, do you also possibly have the implementation for dgc validation?
I'm mostly interested in a working example for RSA validation, which I have a *very* hard time implementing.

**Comment by jeroentrappers** [comment]
Do you mean the schema validation?

**Comment by JChrist** [comment]
Nope, I mean the actual signature verification for certificates signed using an RSA key, such as Sweden `3.json` test file

**Comment by JChrist** [comment]
I'm using [pointycastle](https://pub.dev/packages/pointycastle) and here is my _not working_ attempt (always fails validation):
```dart
final publicKey = RSAPublicKey(rsaModulus, rsaExponent); // extracted from received pem
final signature = RSASignature(signatureData); //signatureData is Uint8List extracted from certificate
final signedData = Uint8List.fromList(expectedSignatureBytes); //expectedSignatureBytes is List<int> calculated from certificate data
//digest identifier hex copied from RSASigner _digestIdentifierHexes
final signer = RSASigner(SHA256Digest(), '0609608648016503040201');
signer.init(false, PublicKeyParameter<RSAPublicKey>(publicKey));

final result = signer.verifySignature(signedData, signature);
```

**Comment by jeroentrappers** [comment]
Using pointycastle did not work for me, as using the RSSSigner is required. I did not get that working either.

I'm using ninja for this. Please check my code, it is there https://github.com/jeroentrappers/dart_cose/blob/bcf7430feb1548d7402d34320becedc9b1199f80/lib/src/cose.dart#L265

**Comment by JChrist** [comment]
Wow! Thanks, checking this out!

**Comment by JChrist** [comment]
Thank you!
It actually works!
I deeply appreciate your response!

**Comment by jeroentrappers** [comment]
You're very welcome
